### PR TITLE
Fix Source Build compiler error

### PR DESCRIPTION
**Pull request by jeffkl**
# Bug

Fixes: 

## Description
Somehow our build started failing after merging https://github.com/NuGet/NuGet.Client/pull/6008. There's an error now that wasn't showing up in its PR build:

```
RestoreTask.cs(108,17): error CS0103: The name 'Debugger' does not exist in the current context
```

This fixes the compiler error.

## PR Checklist

- [ ] Meaningful title, helpful description and a linked NuGet/Home issue
- [ ] Added tests
- [ ] Link to an issue or pull request to update docs if this PR changes settings, environment variables, new feature, etc.

### CODE REVIEW

**Review by KirillOsenkov — APPROVED** [review]

**Comment by KirillOsenkov** [comment]
Oops, my bad! sorry

**Review by zivkan — APPROVED** [review]
