### PR TITLE
Add test cases for PR->PC->PR projects

### LINKED ISSUE #10320: project.assets.json file is missing transitive project dependencies when mixing PackageReference and packages.config with v5.8
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx): 5.8

dotnet.exe --version (if appropriate): 

VS version (if appropriate): vs2019 Latest - MSBuild with /r restore option

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version: v5.7

## Detailed repro steps so we can see the same problem

1. When building a .net461 project from VS 2019 - performs a successful build and projects.assets.json file has all project references with dependencies listed.

 "XX.Credentials.Domain/1.0.0": {
        "type": "project",
        "dependencies": {
          "XX.Access.DataAccess": "1.0.0",
          "XX.Credentials.Formats": "1.0.0"
        },
        "compile": {
          "bin/placeholder/XX.Credentials.Domain.dll": {}
        },
        "runtime": {
          "bin/placeholder/XX.Credentials.Domain.dll": {}
        }
      },

2. When building the same project via Azure Pipelines -> nuget install (v5.8) -> nuget restore -> ms build (v16.8) -> the project.assets.json file misses the project dependencies , hence build failed with assembly missing issues.

 "XX.Credentials.Domain/1.0.0": {
        "type": "project",
        "compile": {
          "bin/placeholder/XX.Credentials.Domain.dll": {}
        },
        "runtime": {
          "bin/placeholder/XX.Credentials.Domain.dll": {}
        }
      },

### LINKED ISSUE #10326: 5.8 + 16.8 Cannot resolve transitive project dependencies when mixing PackageReference and packages.config
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (5.8):
VS version (if appropriate): 16.8.x

Worked before? If so, with which NuGet version
Not entirely sure, but we did not experience an issue before installing 5.8 + 16.8.X
NuGet version (5.7):
VS version (if appropriate): 16.7.x

## Detailed repro steps so we can see the same problem

Given a project dependency chain::

```
TestProject (netcoreapp3.1) 
╚ MvcWebApplication (net461, packages.config old-style csproj) 
  ╚ DependencyA (netstandard2) 
    ╚ TransientProjectB (netstandard2)
```

The TestProject use classes from TransientProjectB directly in a test.

This fails with 
>D:\a\mixed-repro\mixed-repro\TestProject\UnitTest1.cs(3,7): error CS0246: The type or namespace name 'TransientProjectB' could not be found (are you missing a using directive or an assembly reference?) [D:\a\mixed-repro\mixed-repro\TestProject\TestProject.csproj]

The solution builds _fine_ in the IDE (Visual Studio 2019 16.8.X), but not via msbuild on the command line (and hence, not on our build servers).

It's easily enough fixed by adding a direct reference instead of keeping it transient, but was this breaking change on purpose? Why did it work in 16.7 whilst not in 16.8?

### Sample Project
Repo: https://github.com/icenorge/mixed-repro
Build script: https://github.com/icenorge/mixed-repro/blob/master/.github/workflows/MSBuild.yml
Failing build: https://github.com/icenorge/mixed-repro/runs/1453122655?check_suite_focus=true

### PR DESCRIPTION
**Pull request by nkolev92**
## Bug

Fixes: https://github.com/NuGet/Home/issues/10326
Fixes: https://github.com/NuGet/Home/issues/10320
Regression: Yes  
* Last working version:   5.7
* How are we preventing it in future: By adding this test case :)   

## Fix

Details: No product changes here, just covering a test gap. 

## Testing/Validation

Tests Added: Yes  
Reason for not adding tests:  
Validation:

### CODE REVIEW

**Review by erdembayar — APPROVED** [review]

File: test/NuGet.Clients.Tests/NuGet.CommandLine.Test/RestoreNETCoreTest.cs [hunk 1]
```diff
@@ -10135,6 +10140,96 @@ SimpleTestPackageContext createTestPackage(string name, string version, List<Sim
...
+                // A -> B
+                projectA.AddProjectToAllFrameworks(projectB);
+
+                // B -> C
+                projectB.AddProjectToAllFrameworks(projectC);
+
+                // B -> packages.config
+                Util.CreateFile(Path.GetDirectoryName(projectB.ProjectPath), "packages.config",
+@"<packages>
+  <package id=""X"" version=""1.1.0"" targetFramework=""NETStandard1.5"" />
```
Comment (zivkan) [inline test/NuGet.Clients.Tests/NuGet.CommandLine.Test/RestoreNETCoreTest.cs]: I know the targetFramework attribute doesn't really matter, but the project above was created targeting net472, not netstandard1.5.

```suggestion
  <package id=""X"" version=""1.1.0"" targetFramework=""net472"" />
```

**Review by zivkan — APPROVED** [review]
